package com.vtiger.takebizglobal.productTestcases;

import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import com.vtiger.takebizglobal.genericUtility.BaseClass;
import com.vtiger.takebizglobal.pomrepositorylib.CreateProductPage;
import com.vtiger.takebizglobal.pomrepositorylib.HomePage;
import com.vtiger.takebizglobal.pomrepositorylib.ProductInformationPage;
import com.vtiger.takebizglobal.pomrepositorylib.ProductsPage;

//@Listeners(com.vtiger.takebizglobal.genericUtility.ListenerImplementingClass.class)
public class SearchProductTest extends BaseClass{
	
	
	@Test(groups = {"smokeTest"})
	public void SearchProductByProductNumber() throws Throwable {

		//Script data
		String prodName = 	eLib.getDataFromExcel("Sheet1", 1, 2)+randomInt;
		
		HomePage home = new HomePage(driver);
		home.getProductsLink().click();
				
		ProductsPage proPage = new ProductsPage(driver);
		proPage.getCreateProductLink().click();
		System.out.println("Create product page displayed successfully");
		
		CreateProductPage cpp = new CreateProductPage(driver);
		cpp.createNewProduct(prodName);
		System.out.println("Product Information page displayed successfully");
		
		ProductInformationPage pInfoP = new ProductInformationPage(driver);
		String prodNumberGenerated = pInfoP.getAutogeneratedProdNum().getText();
		
		home.getProductsLink().click();
		
		proPage.searchProduct(prodNumberGenerated);
		
	}
	
	@Test(groups = {"regressionTest"})
	public void SearchProductByPartNumber() throws Throwable {

		//Script data
		String prodName = 	eLib.getDataFromExcel("Sheet1", 1, 2)+randomInt;
		String partNumber = eLib.getDataFromExcel("Sheet1", 4, 3);
		
		HomePage home = new HomePage(driver);
		
		
		home.getProductsLink().click();
		System.out.println("Product page displayed successfully");
		
		ProductsPage proPage = new ProductsPage(driver);
		proPage.getCreateProductLink().click();
		System.out.println("Create product page displayed successfully");
		
		CreateProductPage cpp = new CreateProductPage(driver);
		cpp.createNewProduct(prodName, partNumber);
		System.out.println("Product Information page displayed successfully");
		
		ProductInformationPage pInfoP = new ProductInformationPage(driver);
		String prodNumberGenerated = pInfoP.getAutogeneratedProdNum().getText();
		
		home.getProductsLink().click();
		
		proPage.searchProduct(partNumber,prodNumberGenerated, true);
		
		
	}

	@Test(groups = {"regressionTest"})
	public void SearchProductByCommissionRate() throws Throwable {
		//Script data
		String prodName = 	eLib.getDataFromExcel("Sheet1", 1, 2)+randomInt;
		String commRate = (eLib.getDataFromExcel("Sheet1", 7, 4));
		
		HomePage home = new HomePage(driver);
		home.getProductsLink().click();
		
		ProductsPage proPage = new ProductsPage(driver);
		proPage.getCreateProductLink().click();
		
		CreateProductPage cpp = new CreateProductPage(driver);
		cpp.createNewProduct(prodName, commRate, true);
		System.out.println("Product Information page displayed successfully");
		
		ProductInformationPage pInfoP = new ProductInformationPage(driver);
		String prodNumberGenerated = pInfoP.getAutogeneratedProdNum().getText();
		
		home.getProductsLink().click();
		
		proPage.searchProduct(commRate, prodNumberGenerated, true, true);
				
	}
	
}
